### ISSUE TITLE
usb recovery can't work

### ISSUE THREAD

**Issue by fuad99** [ROBOTIS-GIT/ROBOTIS-OP3#100]
I want to recovery my robot using usb flashdrive, at the boot option i select the usb as boot priority, and then nothing happend (not like the tutorial in e-manual)
thanks!

**Comment by ROBOTIS-Will** [comment]
Hi @fuad99 
It is difficult for us to identify the problem you have.
Please make sure that you have downloaded the correct recovery file for your NUC.
When extracting the zip file, please select the USB flashdrive to the target instead of extracting on your local drive and copying the files into the USB drive.
Thank you.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
