### ISSUE TITLE
Control Item was not found on op3_manager

### ISSUE THREAD

**Issue by NurAlif** [ROBOTIS-GIT/ROBOTIS-OP3#113]
I disable every servo except `r_sho_pitch`  with id 1 in my .robot file just for testing purposes.
I flashed protocol 2.0 firmware on my MX-64 with Dynamixel wizard 2.0 recovery. Then, I run op3_manager with my OpenCR board.

output:
```
setting /run_id to 423b778a-cad7-11eb-baa4-26aef6c5ec48
process[rosout-1]: started with pid [9397]
started core service [/rosout]
process[op3_manager-2]: started with pid [9401]
process[op3_localization-3]: started with pid [9415]
[ INFO] [1623431148.851634927]: manager->init
[ INFO] [1623431148.927298741]: Torque on DXLs!
/dev/ttyUSB0 added. (baudrate: 115200)
(/dev/ttyUSB0) [ID:  1]          MX-64 added.
[ WARN] [1623431149.390733409]: Control Item [operating_mode] was not found.
[ WARN] [1623431149.422595502]: Control Item [max_position_limit] was not found.
[ WARN] [1623431149.422695966]: Control Item [min_position_limit] was not found.
[ WARN] [1623431149.525699146]: Control Item [shutdown] was not found.
[ INFO] [1623431149.550835763]: Load offsets...
[ WARN] [1623431149.970710415]: Head control - angle unit : 30
[ INFO] [1623431150.234598676]: parse pose for moving init pose
[ WARN] [1623431150.242715493]: Get the init gain from Dxl init file
[ INFO] [1623431150.378227529]: Go to init pose
[ INFO] [1623431150.385431054]: Base Module is enabled
[ INFO] [1623431150.436911827]: [start] send trajectory
[ INFO] [1623431154.438590524]: [end] send trajectory
```

MX-64 doesn't move but it has torque and its LED is blinking. I turn off and on my OpenCR power switch but the LED is still blinking. I connect my MX-64 with Dynamixel wizard 2.0. I can scan and find my MX-64 but I can't turn the torque, it says overheating when it is actually not hot. 
That servo problem goes away after doing recovery with Dynamixel wizard.

We custom build our OP2 robot and we are planning to upgrade to OP3 but with the same servos. 
Can I use MX's servo for OP3? 
I tried using protocol 1.0 firmware, when i run op3_manager, it says `[RobotisController] first bulk read fail!!`.
Can I use a servo with protocol 1.0 instead?

**Comment by ROBOTIS-Will** [comment]
Hi @NurAlif 

Please understand that we do not provide technical support for customized product.

If you have MX-64 with Protocol 2.0 firmware, it can be used just like X series with some differences such as PID gain values, velocity/current limits.
Since OP3 source code is designed for X series, you'll need to find these differences in the code to create your humanoid.
According to the warning messages, it seems like you didn't set the parameter to initialize each joint in the `dxl_init_OP3.yaml` file.
Please refer to below for configuring a value at start up.
https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/blob/master/op3_manager/config/dxl_init_OP3.yaml#L149

The overheating shutdown occurs when the temperature of the core motor exceeds the configured value and this may not have to do with the ambient temperature or the surface temperature of the product. If you are getting such error, you may have a damaged module.
