### ISSUE TITLE
Linux Mint dependent issues

### ISSUE THREAD

**Issue by yoshimalucky** [ROBOTIS-GIT/ROBOTIS-OP3#7]
Some scripts which are used in ROS community might overwrite /etc/apt/sources.list.d/ros-latest.list because `lsb_release -sc` command returns "serena" instead of "xenial".

**Comment by ROBOTIS-Kayman** [comment]
You are right.
To install ROS, Linux Mint user has to type "sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'" instead of "sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'"
I will update the information to the WIKI.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
